ScreenManager:
    id: screen_manager

    Screen:
        name: "progress"
        BoxLayout:
            orientation: "vertical"
            # size: root.width, root.height
            Label:
                text: ""
                font_size:32
            Label:
                text: "LOGO"
                font_size:32

            ProgressBar:
                id: progress_bar
                min:0
                max:100
                pos_hint: {"x":.1, "y":.1}
                size_hint_x: .8
                # value:root.progress_value
                # on_release: app.root.current = "second"
            
            Label:
                text: ""
                font_size:32
            
            Label:
                text: ""
                font_size:32

    Screen:
        name: 'second'
        username:username
        new_username:new_username

        BoxLayout:
            orientation: 'vertical'
            Label:
                text: ""
                font_size:32
            TextInput:
                id: username
                multiline: False
            Label:
                text: ""
                font_size:32
            TextInput:
                id: new_username
                multiline: False
            
            Button:
                text: "Submit"
                multiline: False
                hint_text: "Enter your Username: "
                on_press: app.on_text_input_change()


            Label:
                text: ""
                font_size:32
            